const APP = {
  CHARACTERS: {
    GET_LIST: 'VIEWS:CHARACTERS:GET_LIST',
    LIST_RECEIVING: 'VIEWS:CHARACTERS:LIST_RECEIVING',
    LIST_RECEIVING_ERROR: 'VIEWS:CHARACTERS:LIST_RECEIVING_ERROR',
    LIST_RECEIVED: 'VIEWS:CHARACTERS:LIST_RECEIVED',

    SET_LIST_FILTER: 'VIEWS:CHARACTERS:SET_LIST_FILTER',
    SET_FAVORITE_SWITCHER: 'VIEWS:CHARACTERS:SET_FAVORITE_SWITCHER',

    SET_FAVORITE_STATE: 'VIEWS:CHARACTERS:SET_CHARACTER_FAVORITE_STATE',
    FAVORITE_STATE_CHANGING: 'VIEWS:CHARACTERS:FAVORITE_STATE_CHANGING',
    FAVORITE_STATE_CHANGING_ERROR: 'VIEWS:CHARACTERS:FAVORITE_STATE_CHANGING_ERROR',
    FAVORITE_STATE_CHANGED: 'VIEWS:CHARACTERS:FAVORITE_STATE_CHANGED',

    SET_MODAL_SOURCE: 'VIEWS:CHARACTERS:SET_MODAL_SOURCE',
    SET_MODAL_ERRORS: 'VIEWS:CHARACTERS:SET_MODAL_ERRORS',

    SAVE: 'VIEWS:CHARACTERS:SAVE',
    SAVING: 'VIEWS:CHARACTERS:SAVING',
    SAVING_ERROR: 'VIEWS:CHARACTERS:SAVING_ERROR',
    SAVED: 'VIEWS:CHARACTERS:SAVED',

    DELETE: 'VIEWS:CHARACTERS:DELETE',
    DELETING: 'VIEWS:CHARACTERS:DELETING',
    DELETING_ERROR: 'VIEWS:CHARACTERS:DELETING_ERROR',
    DELETED: 'VIEWS:CHARACTERS:DELETED',
  },
};

export default APP;
